package:
  name: esmpy
  version: {{ environ['CONDA_ESMF_VER'] }}

build:
  number: {{ environ['CONDA_ESMF_BNO'] }}

source:
  git_url: git://git.code.sf.net/p/esmf/esmf
  git_tag: {{ environ['CONDA_ESMF_TAG'] }}

requirements:
  build:
    - python
    - numpy
    - esmf =={{ environ['CONDA_ESMF_VER'] }}

    # ===== Required for testing. =====
    - nose
    - netcdf4
    # =================================
  run:
    - python
    - numpy
    - esmf =={{ environ['CONDA_ESMF_VER'] }}

test:
  imports:
    - ESMF

about:
  home: https://www.earthsystemcog.org/projects/esmpy/
  license: The University of Illinois/NCSA Open Source License (NCSA)
  license_file: LICENSE
  summary: ESMPy is a Python interface to the Earth System Modeling Framework (ESMF) regridding utility.
